import type { DjSong } from "./types";

export const DJ_SONG_CATALOG: DjSong[] = [
  {
    id: "newera-birds",
    title: "Birds In The Sky",
    artist: "NewEra",
    bpm: 92,
    energy: 2,
    soundCloudUrl: "https://api.soundcloud.com/tracks/1668658005",
    tags: ["warmup", "melodic"],
  },
  {
    id: "banks-before",
    title: "Before I Ever Met You",
    artist: "BANKS",
    bpm: 102,
    energy: 2,
    soundCloudUrl: "https://api.soundcloud.com/tracks/77796678",
    tags: ["steady", "vocal"],
  },
  {
    id: "banks-work",
    title: "Work",
    artist: "BANKS",
    bpm: 118,
    energy: 3,
    soundCloudUrl: "https://api.soundcloud.com/tracks/74570624",
    tags: ["steady", "vocal"],
  },
  {
    id: "nianaro-abbey",
    title: "Abbey",
    artist: "Nianaro",
    bpm: 133,
    energy: 4,
    soundCloudUrl: "https://api.soundcloud.com/tracks/217193295",
    tags: ["run", "trance"],
  },
  {
    id: "mord-1984",
    title: "1984",
    artist: "Mord Fustang",
    bpm: 128,
    energy: 4,
    soundCloudUrl: "https://api.soundcloud.com/tracks/187008644",
    tags: ["push", "electro"],
  },
  {
    id: "mord-press-start",
    title: "PRESS START",
    artist: "Mord Fustang",
    bpm: 140,
    energy: 5,
    soundCloudUrl: "https://api.soundcloud.com/tracks/187009032",
    tags: ["interval", "electro"],
  },
  {
    id: "manta-its-you",
    title: "It's You",
    artist: "Manta",
    bpm: 174,
    energy: 5,
    soundCloudUrl: "https://api.soundcloud.com/tracks/1846545519",
    tags: ["sprint", "drum-and-bass"],
  },
];
